### ISSUE TITLE
Obtención de crédito disponible

### ISSUE THREAD

**Issue by edudele** [MiguelAngelLV/octopus_spain#11]
Buenas noches,
 nose si la API lo permite pero con esto de los referidos, a todos nos han acabado metiendo algo de crédito en la cuenta.

Nose si sería posible añadir el credito para poder tener un seguimiento de ese crédito, como se hace ahora con la BV, la app si lo permite ver.(adjunto captura)
![Screenshot_2024-01-07-19-43-13-884_energy octopus octopusenergy android](https://github.com/MiguelAngelLV/octopus_spain/assets/2486525/4f155f9d-89a3-4c9a-915b-66b23c46a7e0)

Muchas gracias por el curro un saludo.

**Comment by MiguelAngelLV** [comment]
Ya lo tienes.

Actualiza a la versión 1.1 y tendrás la entidad «Octopus Credit» :smile:
