### ISSUE TITLE
STATE_CLASS_MEASUREMENT should be replaced with SensorStateClass.MEASUREMENT

### ISSUE THREAD

**Issue by johanhellman** [MiguelAngelLV/octopus_spain#12]
Core 2024.1.5
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

From HA logs: 

Logger: homeassistant.components.sensor
Source: helpers/deprecation.py:205
Integration: Sensor (documentation, issues)
First occurred: 08:31:48 (2 occurrences)
Last logged: 08:31:48

STATE_CLASS_MEASUREMENT was used from octopus_spain, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please create a bug report at https://github.com/MiguelAngelLV/issues

**Comment by MiguelAngelLV** [comment]
Cuando saque la próxima versión lo corregiré. Ahora mismo solo es un aviso de que a partir del 2025 fallará, pero por ahora funciona correctamente.

**Comment by MiguelAngelLV** [comment]
Solucionado (a final casi me pilla...)
