### ISSUE TITLE
GRACIAS POR EL COMPLEMENTO

### ISSUE THREAD

**Issue by Gerap93** [MiguelAngelLV/octopus_spain#13]
Hola Miguel,

Muchas gracias por tu complemento, ver que se abren al usuario ha sido uno de los motivos por los que me he cambiado a Octopus. 

Mi consulta consiste en si también podría ser posible medir los consumos, ¿la API no está liberada en España?

¡Muchas gracias de nuevo!

**Comment by MiguelAngelLV** [comment]
Creo que hay una API que devuelve datos sobre tu consumo en los últimos días, pero no en tiempo real. Realmente lo que hace es leer los datos de tu distribuidora y devolvertelos. 

Sin embargo, implementar esto es bastante complejo y dado que  existe un complemento que ya lo hace con cualquier comercializadora/distribuidora española (https://github.com/uvejota/homeassistant-edata), no creo que merezca la pena.
