### ISSUE TITLE
Lista de entidades incompletas

### ISSUE THREAD

**Issue by Aresitoo** [MiguelAngelLV/octopus_spain#5]
![Screenshot_20230531-112552](https://github.com/MiguelAngelLV/octopus_spain/assets/85060696/a480d176-fbf2-4dd0-a4ec-88ef85d8654b)

Hola! A mi solo me saca dos entidades 

- solar Wallet
- última factura

**Comment by MiguelAngelLV** [comment]
Correcto. Esas son las dos únicas entidades que deben salir (salvo que tengas varias cuentas que saldrá 2 entidades por cuenta).

En última factura, en **atributos**, tienes los datos que supongo que buscas (fecha emisión, fecha de inicio y fecha de final)

**Comment by Aresitoo** [comment]
Vale! No me habia quedado claro en el readme!
Disculpas

**Comment by MiguelAngelLV** [comment]
He actualizado el readme porque es cierto que no quedaba especialmente claro salvo que analices el ejemplo del card.
