### ISSUE TITLE
Como obtener la API para consultas a la cuenta de Octopus España

### ISSUE THREAD

**Issue by ppnacho** [MiguelAngelLV/octopus_spain#6]
Hola,

Como se puede conseguir la API para poder hacer consultas, he visto que para Octopus Energy si se puede pero en el caso de la compañia que opera en España no encuentro nada.

Muchas Gracias,

**Comment by MiguelAngelLV** [comment]
No tengo claro a que te refieres. 

Este componente es para la Octopus Energy España y usa su API. Si miras como está hecho, verás que conecta con una API GraphQL.

La API realmente no es pública (no vas encontrar en su web como usarla ni nada), es la que usan ellos para su web y seguramente para su futura aplicación, pero no tiene ningún tipo de bloqueo así que es relativamente fácil de usar.

Aquí puedes ver las llamadas que realiza el componente (muy básicas), pero si investigas un poco el endpoint de Graphql verás que tiene bastantes más campos:

https://github.com/MiguelAngelLV/octopus_spain/blob/main/custom_components/octopus_spain/lib/octopus_spain.py

PD: Hasta dónde yo sé, temas de consumo y demás no hay
