### ISSUE TITLE
La integración ha dejado de funcionar

### ISSUE THREAD

**Issue by DaniGP315** [MiguelAngelLV/octopus_spain#7]
Hola, no se si seré un caso particular o es un problema interno de Octopus, pero la integración me dejó de funcionar esta mañana.

La entidades han dejado de funcionar aunque recargue la integración no se soluciona.
![Captura1](https://github.com/MiguelAngelLV/octopus_spain/assets/78767353/3391c326-c2d4-4b2a-a9c1-21b67e90f1c9)

He usado directamente la API de Octopus y obtengo errores internos:
![Captura3](https://github.com/MiguelAngelLV/octopus_spain/assets/78767353/8c3bca78-8131-407a-89c6-958357ae055a)

Parece que son debidos a que obtengo:
   "amount": null,
   "consumptionStartDate": null,
   "consumptionEndDate": null,

![Captura4](https://github.com/MiguelAngelLV/octopus_spain/assets/78767353/31512965-bb1f-4537-aaa3-9e69fda7909e)

Espero que esta información les sea útil. Un saludo.

**Comment by MPAndrew** [comment]
A mí me ha pasado lo mismo.

**Comment by MiguelAngelLV** [comment]
Pero es porque si servidor falla. Si intentáis ver las facturas desde la web pasa también. 

Habrá que esperar a que lo arreglen.

**Comment by DaniGP315** [comment]
Tienes razón no verifiqué desde la propia web de Octopus.

**Comment by MiguelAngelLV** [comment]
> Tienes razón no verifiqué desde la propia web de Octopus.

Lástima no verificases la web... Ya tengo la hoguera lista. Venga, adentro... ¡Vamos!, ¡jop jop!

**Comment by MiguelAngelLV** [comment]
Ya han resuelto la incidencia en el servidor y vuelve a funcionar la integración. Puede tardar un par de horas en salir como activa ya que actualiza cada X horas.

PD: Si habéis quitado la integración tendréis que volver a añadirla o reiniciar al menos.
