### ISSUE TITLE
Dos contratos. Segunda factura 0€

### ISSUE THREAD

**Issue by mapeai** [MiguelAngelLV/octopus_spain#9]
Tengo dos contratos asociados a la cuenta que ha detectado perfectamente el add-on. EL primero de ellos sí me aparece el valor correcto de la factura pero en el segundo me aparece 0€. El resto de información sí es correcta.

Gracias por el trabajo.

Un saludo

**Comment by MiguelAngelLV** [comment]
Parece que hay un error en la API de Octopus, ya lo he reportado, estoy a la espera de que me respondan.
